blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/locnguyen0904/express-typescript-boilerplate#readme
    about: Check the documentation before opening an issue
